#!/usr/bin/env python3

import os
import sys
import re
import json
import numpy as np
import shlex
import subprocess
import chevron
from pprint import pprint
from subprocess import Popen, PIPE
#from julia.api import Julia
#import csv
import pandas as pd
pd.set_option("display.precision",16)

import argparse
from datetime import datetime
from pathlib import Path
from termcolor import colored

def warn(msg):
    print(colored("[WARN] " + msg, "red"))

MAX_PROCS = 5

def poll_all(procs):
    for p in list(procs):
        poll = p['p'].poll()
        if poll is not None:
            procs.remove(p)
            p['logs'].close()
            if p['p'].returncode != 0:
                warn(f"Failed: {p['mnemonic']} / {p['file']}")

def main(args):
    args.dir = Path(args.dir)
    
    with open(args.dir / 'config' / 'config.json', 'r') as io:
        args.config = json.load(io)

    with open(args.dir / 'instances.json', 'r') as io:
        instances = json.load(io)
        
    procs = []
    for (mnemonic, noise_level) in args.config['NOISE_LEVEL'].items():
        copy_dir = output_dir / f"copy_{mnemonic}"
        results_dir = copy_dir / ESTIMATION_RESULTS_DIR
        print(f"\nNOISE LEVEL: {noise_level}")
        print(f"  CLEANING RESULTS: {results_dir}")
        for root, dirs, files in os.walk(results_dir):
            for file in files:
                os.remove(Path(root) / file)
        print(f"  RUNNING FILES IN: {copy_dir / ESTIMATION_DIR}")
        for root, dirs, files in os.walk(copy_dir / ESTIMATION_DIR):
            for file in files:
                while len(procs) >= MAX_PROCS:
                    poll_all(procs)             
                print("    ", file)
                cmd = shlex.split('julia ' + str(Path(root) / file))
                log_file = open(str(copy_dir / ESTIMATION_RESULTS_DIR / (file + ".log")), "w")
                try:
                    p = Popen(cmd, stdout=log_file, stderr=log_file)
                    procs.append(dict(mnemonic=mnemonic, file=file, p=p, logs=log_file))
                except subprocess.CalledProcessError:
                    print("Error excepted. Settings:")
                    print(file)
                    continue
    while len(procs) > 0:
        poll_all(procs)  
    
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("dir", help="The directory generated by generate.py.")
    args = parser.parse_args()
    
    main(args)

