#!/usr/bin/env python3

import os
import sys
import re
import json
import tqdm
import numpy as np
import shlex
import subprocess
import chevron
from pprint import pprint
from subprocess import Popen, PIPE
import shutil
import pandas as pd
pd.set_option("display.precision",16)

import argparse
from datetime import datetime
import time
from pathlib import Path
from termcolor import colored

from shared import warn, info, get_settings, AVAILABLE_SOFTWARE, END_OF_LOG, STDOUT_FILENAME, STDERR_FILENAME

def get_cmd(args, instance):
    if args.software in ['pe','odepe','sciml','odepe_kernel_se','odepe_kernel_rq','odepe_kernel_se_plus_rq','odepe_kernel_se_times_rq']:
        return shlex.split('julia ' + str(args.dir.resolve().absolute() / args.config['FILETREE'] / args.run / instance['id'] / f"script.jl"))
    elif args.software in ['amigo2', 'iqm']:
        return shlex.split('matlab -singleCompThread -nodisplay -nosplash -nodesktop -licmode onlinelicensing -r "run ' + str(args.dir.resolve().absolute() / args.config['FILETREE'] / args.run / instance['id'] / f"script.m") + '; exit"')
    else:
        warn(f"Do not know this software: {args.software}")

def get_slurm_job_timeout(job_id):
    if not job_id or shutil.which("scontrol") is None:
        return None
    try:
        command = ["scontrol", "show", "job", str(job_id)]
        result = subprocess.run(command, capture_output=True, text=True, check=True)
        output = result.stdout
        match = re.search(r"TimeLimit=(\S+)", output)
        if match:
            return match.group(1)
        else:
            return None
    except:
        return None

def _main(args):
    with open(args.dir / 'huge_json.json', 'r') as io:
        instances = json.load(io)
    for index in args.array:
        instance = instances['instances'][index]
        assert instance['index'] == index
        print(instance['id'])
        cmd = get_cmd(args, instance) 
        stdout_filepath = str(args.dir / args.config['FILETREE'] / args.run / instance['id'] / STDOUT_FILENAME)
        stdout_file = open(stdout_filepath, "w")
        stderr_filepath = str(args.dir / args.config['FILETREE'] / args.run / instance['id'] / STDERR_FILENAME)
        stderr_file = open(stderr_filepath, "w")
        slurm_job_id = os.environ.get("SLURM_JOB_ID")
        slurm_task_id = os.environ.get("SLURM_ARRAY_TASK_ID")
        print(f"### Run on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", file=stdout_file)
        slurm_timeout = get_slurm_job_timeout(slurm_job_id)
        print(f"### SLURM job timeout: {slurm_timeout}", file=stdout_file)
        slurm_env = filter(lambda kv: kv[0].startswith('SLURM_'), list(os.environ.items()))
        slurm_env = sorted(slurm_env, key=lambda kv: kv[0])
        for key, value in slurm_env:
            print(f"### {key}: {value}", file=stdout_file)
        stdout_file.flush()
        start_time = time.time()
        try:
            p = subprocess.run(cmd, stdout=stdout_file, stderr=stderr_file)
        except subprocess.CalledProcessError:
            warn(f"Error for {instance['id']}.")
        finally:
            print(f"\n\nTime: {time.time() - start_time}\n{END_OF_LOG}", file=stdout_file)
            stdout_file.close()
            stderr_file.close()

def main(args):
    assert args.software in AVAILABLE_SOFTWARE
    
    args.dir = Path(args.dir)
    with open(args.dir / 'config' / 'config.json', 'r') as io:
        args.config = json.load(io)

    with open(args.dir / 'huge_json.json', 'r') as io:
        instances = json.load(io)

    info(f"There are {len(instances['instances'])} instances in total: {0}-{len(instances['instances'])-1}.")

    if args.array == 'all':
        args.array = f"{0}-{len(instances['instances'])-1}"
    args.array = sum(map(lambda x: [int(x)] if '-' not in x else list(range(int(x.split('-')[0]), 1+int(x.split('-')[1]))), args.array.split(',')), [])
    args.array = sorted(list(set(args.array)))

    print(args.dir.resolve().absolute() / args.config['FILETREE'] / args.run)
    assert 0 <= args.array[0]
    assert args.array[-1] < len(instances['instances'])
    assert (args.dir.resolve().absolute() / args.config['FILETREE'] / args.run).exists()

    print(f"""
###  RUNNING ESTIMATION SCRIPTS  ###

SOFTWARE            {args.software}
ARRAY               {args.array}
DIR                 {args.dir}

OUTPUT:             {args.dir}
    RESULTS:        {args.dir / args.config['FILETREE'] / args.run}
""")
    
    _main(args)
    
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("dir", help="The directory generated by generate_data.py.")
    parser.add_argument("run", help="The directory generated by generate_scripts.py.")
    parser.add_argument("software", help="The software to run estimation for. Possible choices are: {}.".format(', '.join(AVAILABLE_SOFTWARE)))
    parser.add_argument("array", help="Array undices of jobs, e.g., 0,3,4-11, or 'all'")
    args = parser.parse_args()
    
    main(args)
