#!/usr/bin/env python3

import os
import sys
import re
import json
import tqdm
import numpy as np
import shlex
import subprocess
import chevron
from pprint import pprint
from subprocess import Popen, PIPE
import shutil
#from julia.api import Julia
#import csv
import pandas as pd
pd.set_option("display.precision",16)

import argparse
from datetime import datetime
from pathlib import Path
from termcolor import colored

from shared import warn, get_settings, AVAILABLE_SOFTWARE

def main_julia(args):
    with open(args.dir / 'huge_json.json', 'r') as io:
        instances = json.load(io)

    assert 0 <= args.array[0]
    assert args.array[-1] < len(instances['instances'])

    for index in args.array:
        instance = instances['instances'][index]
        print(instance['id'])
        cmd = shlex.split('julia ' + str(args.dir.resolve().absolute() / args.config['FILETREE'] / args.software / instance['id'] / f"script.jl"))
        log_filepath = str(args.dir / args.config['FILETREE'] / args.software / instance['id'] / ('log' + '.txt'))
        log_file = open(log_filepath, "w")
        try:
            p = subprocess.run(cmd, stdout=log_file, stderr=log_file)
        except subprocess.CalledProcessError:
            warn(f"Error for {instance['id']}.")
        finally:
            log_file.close()

def main_amigo2(args):
    with open(args.dir / 'huge_json.json', 'r') as io:
        instances = json.load(io)

    assert 0 <= args.array[0]
    assert args.array[-1] < len(instances['instances'])
    for index in args.array:
        instance = instances['instances'][index]
        print(instance['id'])
        cmd = shlex.split('matlab -nodisplay -nosplash -nodesktop -r "run ' + str(args.dir.resolve().absolute() / args.config['FILETREE'] / args.software / instance['id'] / f"script.m") + '; exit"')
        log_filepath = str(args.dir / args.config['FILETREE'] / args.software / instance['id'] / ('log' + '.txt'))
        log_file = open(log_filepath, "w")
        try:
            p = subprocess.run(cmd, stdout=log_file, stderr=log_file)
        except subprocess.CalledProcessError:
            warn(f"Error for {instance['id']}.")
        finally:
            log_file.close()

def main(args):
    assert args.software in AVAILABLE_SOFTWARE
    
    args.dir = Path(args.dir)
    with open(args.dir / 'config' / 'config.json', 'r') as io:
        args.config = json.load(io)

    assert (args.dir.resolve().absolute() / args.config['FILETREE'] / args.software).exists()

    args.array = sum(map(lambda x: [int(x)] if '-' not in x else list(range(int(x.split('-')[0]), 1+int(x.split('-')[1]))), args.array.split(',')), [])
    args.array = sorted(list(set(args.array)))

    print(f"""
###  RUNNING ESTIMATION SCRIPTS  ###

SOFTWARE            {args.software}
ARRAY               {args.array}
DIR                 {args.dir}

OUTPUT:             {args.dir}
    RESULTS:        {args.dir / args.config['FILETREE'] / args.software}
""")

    if args.software in ['pe', 'sciml', 'odepe']:
        main_julia(args)
    elif args.software in ['amigo2']:
        main_amigo2(args)
    else:
        exit(1)
    
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("dir", help="The directory generated by generate_data.py.")
    parser.add_argument("software", help="The software to run estimation for. Possible choices are: {}.".format(', '.join(AVAILABLE_SOFTWARE)))
    parser.add_argument("array", help="Array undices of jobs, e.g., 0,3,4-11")
    args = parser.parse_args()
    
    main(args)

