#!/usr/bin/env python3

import os
import sys
import re
import json
import tqdm
import numpy as np
import shlex
import subprocess
import chevron
from pprint import pprint
from subprocess import Popen, PIPE
import shutil
#from julia.api import Julia
#import csv
import pandas as pd
pd.set_option("display.precision",16)

import argparse
from datetime import datetime
from pathlib import Path
from termcolor import colored

from shared import warn, get_settings, AVAILABLE_SOFTWARE

TEMPLATE_ESTIMATION = {
    "pe"     : "templates/julia_template_for_estimation.jl",
	"odepe"  : "templates/julia_template_for_estimation_odepe.jl",
    "amigo2" : "templates/amigo2.m.template" 
}

FILE_EXT = {'pe': 'jl', 'odepe': 'jl', 'sciml': 'jl', 'amigo2': 'm'}

def main(args):
    assert args.software in AVAILABLE_SOFTWARE
    
    args.dir = Path(args.dir)
    
    with open(args.dir / 'config' / 'config.json', 'r') as io:
        args.config = json.load(io)
        
    with open(args.dir / 'huge_json.json', 'r') as io:
        instances = json.load(io)

    print(f"""
###  GENERATING RUNNABLE FILES  ###

SOFTWARE            {args.software}

TEMPLATE            {TEMPLATE_ESTIMATION[args.software]}

OUTPUT:             {args.dir}
    SCRIPTS:        {args.dir / args.config['FILETREE'] / args.software}
""")

    if os.path.exists(args.dir / args.config['FILETREE'] / args.software):
        warn(f"Deleting existing {args.dir / args.config['FILETREE'] / args.software}")
        shutil.rmtree(args.dir / args.config['FILETREE'] / args.software)
        
    shutil.copytree(args.dir / args.config['FILETREE'] / args.config['DATA_DIR_NOISY'], args.dir / args.config['FILETREE'] / args.software)
    
    for instance in instances['instances']:
        print(instance['id'])

        if args.software in ['pe','odepe','sciml','amigo2']:
            settings = get_settings(args, instance)
            settings["data_filepath"] = 'data.csv'
            settings["estimation_result_filepath"] = 'result.csv'
            settings["at_time"] = (args.config['TIME_INTERVAL'][1] - args.config['TIME_INTERVAL'][0])/2 + args.config['TIME_INTERVAL'][0]
            settings["data_expr"] = instance["sciml_measurements"]
            with open(args.dir / args.config['FILETREE'] / args.software / instance['id'] / f'script.{FILE_EXT[args.software]}', 'w') as output_file:
                testfile = chevron.render(open(TEMPLATE_ESTIMATION[args.software]), settings, warn=True)
                output_file.write(testfile)
    
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("dir", help="The directory generated by generate_data.py.")
    parser.add_argument("software", help="The software to generate scripts for. Possible choices are: {}.".format(', '.join(AVAILABLE_SOFTWARE)))
    args = parser.parse_args()
    
    main(args)
