import sys
import getpass
from datetime import datetime
from termcolor import colored

AVAILABLE_SOFTWARE = ['pe', 'odepe', 'sciml', 'iqm', 'amigo2']

END_OF_LOG = "===END==="

STDOUT_FILENAME = "stdout.txt"
STDERR_FILENAME = "stderr.txt"

JULIA_ENVIRONMENTS = {
    "pe"    : "Symbol(:environments, /, :julia_pe)",
    "odepe" : "Symbol(:environments, /, :julia_odepe)",
    "sciml" : "Symbol(:environments, /, :julia_sciml)",
    "amigo2": "",
    "iqm"   : ""
}

def warn(msg):
    print(colored("[WARN] " + msg, "red"))

def info(msg):
    print(colored("[INFO] " + msg, "blue"))

def get_file_meta_header(comment):
    file_meta_header = f"""{comment}{comment}{comment} This file is machine-generated.
{comment*3} Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
{comment*3} Author: {getpass.getuser()}
{comment*3} Generated by: {" ".join(sys.argv)}
{comment*3} Environment: {sys.prefix}

"""
    return file_meta_header

def get_settings(args, instance):
    state_variables = instance["state_variables"]
    states = []
    for i, varname in enumerate(state_variables):
        states.append({
            "varname": varname,
            "value": instance['state_values'][varname],
            "comma": ", " if i < len(state_variables)-1 else "",
            "space": " " if i < len(state_variables)-1 else "",
        })
    parameter_variables = instance["parameter_variables"]
    parameters = []
    for i, varname in enumerate(parameter_variables):
        parameters.append({
            "varname": varname,
            "comma": ", " if i < len(parameter_variables)-1 else "",
            "space": " " if i < len(parameter_variables)-1 else "",
            "true": instance['parameter_values'][varname]
        })
    instance = instance | {
        "states": states,
        "parameters": parameters,
        "time_start": args.config['TIME_INTERVAL'][0],
        "time_end": args.config['TIME_INTERVAL'][1],
        "count": args.config['NUM_PTS'],
    }
    
    instance_name = instance["name"]
    time = instance["time"]
    state_variables = instance["state_variables"]
    states = []
    for i, varname in enumerate(state_variables):
        states.append({
            "varname": varname,
            "comma": ", " if i < len(state_variables)-1 else "",
            "space": " " if i < len(state_variables)-1 else "",
        })
    measurement_variables = instance["measurement_variables"]
    measurements = []
    for i, varname in enumerate(measurement_variables):
        measurements.append({
            "varname": varname,
            "comma": ", " if i < len(measurement_variables)-1 else "",
            "space": " " if i < len(measurement_variables)-1 else "",
        })
    parameter_variables = instance["parameter_variables"]
    parameters = []
    for i, varname in enumerate(parameter_variables):
        parameters.append({
            "varname": varname,
            "comma": ", " if i < len(parameter_variables)-1 else "",
            "space": " " if i < len(parameter_variables)-1 else "",
            "true": instance['parameter_values'][varname],
        })
    components = []
    for i, state_var in enumerate(state_variables):
        components.append({
            "state_var": state_var,
            "state_expr": instance["ode_system"][state_var],
            "comma": ", " if i < len(state_variables)-1 else "",
        })
    measured_quantities = []
    for i, measure_var in enumerate(instance['measurement_variables']):
        measured_quantities.append({
            "measurement": measure_var,
            "measurement_expression": instance['measurements'][measure_var],
            "index": i+1,
            "comma": ", " if i < len(measurement_variables)-1 else "",
        })
    measured_quantities_amigo2 = []
    for i, measure_var in enumerate(instance['measurement_variables']):
        measured_quantities_amigo2.append({
            "measurement": measure_var,
            "measurement_expression": instance['measurements'][measure_var].replace('*', '.*'),
            "index": i+1,
            "comma": ", " if i < len(measurement_variables)-1 else "",
        })

    initial_conditions = []
    for i, state_var in enumerate(state_variables):
        initial_conditions.append({
            "value": instance['state_values'][state_var],
            "comma": ", " if i < len(state_variables)-1 else "",
        })


    settings = {
        "name": instance_name, #re.sub(".jl$", "" , instance_name),
        "states": states,
        "num_states": len(states),
        "measurements": measurements,
        "num_measurements": len(measurements),
        "parameters": parameters,
        "num_parameters": len(parameters),
        "components": components,
        "measured_quantities": measured_quantities,
        "measured_quantities_amigo2": measured_quantities_amigo2,
        "initial_conditions": initial_conditions,
        "time_start": instance["time"]["start"],
        "time_end": instance["time"]["end"],
        "duration": instance["time"]["end"] - instance["time"]["start"],
        "time_count": instance["time"]["count"],
        "lower_bound": args.config['SEARCH_BOUNDS'][0],
        "upper_bound": args.config['SEARCH_BOUNDS'][1]
    }

    if 'data' in instance:
        settings["data"] = '\n'.join([' '.join([str(instance['data'][j][i]) for j in range(1, len(instance['data']))]) for i in range(len(instance['data'][0]))])
        settings["data_with_time"] = '\n'.join([','.join([str(instance['data'][j][i]) for j in range(0, len(instance['data']))]) for i in range(len(instance['data'][0]))])

    return settings
    
