import sys
import hashlib
from datetime import datetime
from termcolor import colored

AVAILABLE_SOFTWARE = ['pe', 'odepe', 'sciml', 'amigo2',
                      'odepe_kernel_se', 'odepe_kernel_rq',
                      'odepe_kernel_se_plus_rq', 'odepe_kernel_se_times_rq',
                      'odepe_multipoint',
                      'odepe_v2_polish', 'odepe_v2_nopolish', 'odepe_shade']  # 'iqm'

END_OF_LOG = "===END==="

STDOUT_FILENAME = "stdout.txt"
STDERR_FILENAME = "stderr.txt"
FAILURE_REASON_FILENAME = "failure_reason.txt"
WALL_TIME_FILENAME = "wall_time_seconds.txt"
CELL_SEED_FILENAME = "cell_seed.txt"
DATA_HASH_FILENAME = "data.csv.sha256"

# Failure reason category tokens. The first line of failure_reason.txt MUST be one of these
# (or "unknown" as a last resort); subsequent lines hold a free-form traceback / detail.
# Keep this list extensible — add new tokens as new failure modes are observed.
FAILURE_REASON_TOKENS = (
    "julia_exception",
    "matlab_exception",
    "mklJac_crash",
    "slurm_timeout",
    "slurm_oom",
    "mex_compile_failed",
    "no_estimated_section",
    "data_hash_mismatch",
    "unknown",
)

JULIA_ENVIRONMENTS = {
    "pe"    : "Symbol(:environments, /, :julia_pe)",
    "odepe" : "Symbol(:environments, /, :julia_odepe)",
    "sciml" : "Symbol(:environments, /, :julia_sciml)",
    "amigo2": "",
    "iqm"   : "",
    "odepe_kernel_se"         : "Symbol(:environments, /, :julia_odepe)",
    "odepe_kernel_rq"         : "Symbol(:environments, /, :julia_odepe)",
    "odepe_kernel_se_plus_rq" : "Symbol(:environments, /, :julia_odepe)",
    "odepe_kernel_se_times_rq": "Symbol(:environments, /, :julia_odepe)",
    "odepe_multipoint"        : "Symbol(:environments, /, :julia_odepe)",
    "odepe_v2_polish"         : "Symbol(:environments, /, :julia_odepe)",
    "odepe_v2_nopolish"       : "Symbol(:environments, /, :julia_odepe)",
    "odepe_shade"             : "Symbol(:environments, /, :julia_odepe)",
}


def cell_seed(system_name: str, instance_idx: int, noise_mnemonic: str) -> int:
    """Stable 32-bit RNG seed for a (system, instance, noise) cell.

    Uses md5 over a canonical string. Re-running with the same tuple gives a
    bit-identical seed, regardless of: process, machine, prior calls, system
    list ordering, or any unrelated harness state. Adding or reordering
    systems in `systems.json` does not perturb existing instances' seeds.

    `noise_mnemonic` is the key from `config.json`'s `NOISE_LEVEL` dict
    (e.g. "0e+00", "1e-08"); use the literal string "noise_free" for the
    parameter/IC sampling pass that runs before noise is applied.
    """
    h = hashlib.md5(f"{system_name}_{instance_idx}_{noise_mnemonic}".encode()).hexdigest()[:8]
    return int(h, 16)

def warn(msg):
    print(colored("[WARN] " + msg, "red"))

def info(msg):
    print(colored("[INFO] " + msg, "blue"))

def get_file_meta_header(comment):
    file_meta_header = f"""{comment}{comment}{comment} This file is machine-generated.
{comment*3} Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
{comment*3} Generated by: {" ".join(sys.argv)}
{comment*3} Environment: {sys.prefix}

"""
    return file_meta_header

def get_settings(args, instance):
    state_variables = instance["state_variables"]
    states = []
    for i, varname in enumerate(state_variables):
        states.append({
            "varname": varname,
            "value": instance['state_values'][varname],
            "comma": ", " if i < len(state_variables)-1 else "",
            "space": " " if i < len(state_variables)-1 else "",
        })
    parameter_variables = instance["parameter_variables"]
    parameters = []
    for i, varname in enumerate(parameter_variables):
        parameters.append({
            "varname": varname,
            "comma": ", " if i < len(parameter_variables)-1 else "",
            "space": " " if i < len(parameter_variables)-1 else "",
            "true": instance['parameter_values'][varname]
        })
    # Use per-instance time if available (set from per-model time_interval in generate_data)
    time_start = instance.get("time", {}).get("start", args.config['TIME_INTERVAL'][0])
    time_end = instance.get("time", {}).get("end", args.config['TIME_INTERVAL'][1])
    instance = instance | {
        "states": states,
        "parameters": parameters,
        "time_start": time_start,
        "time_end": time_end,
        "count": args.config['NUM_PTS'],
    }
    
    instance_name = instance["name"]
    time = instance["time"]
    state_variables = instance["state_variables"]
    states = []
    for i, varname in enumerate(state_variables):
        states.append({
            "varname": varname,
            "comma": ", " if i < len(state_variables)-1 else "",
            "space": " " if i < len(state_variables)-1 else "",
        })
    measurement_variables = instance["measurement_variables"]
    measurements = []
    for i, varname in enumerate(measurement_variables):
        measurements.append({
            "varname": varname,
            "comma": ", " if i < len(measurement_variables)-1 else "",
            "space": " " if i < len(measurement_variables)-1 else "",
        })
    parameter_variables = instance["parameter_variables"]
    parameters = []
    for i, varname in enumerate(parameter_variables):
        parameters.append({
            "varname": varname,
            "comma": ", " if i < len(parameter_variables)-1 else "",
            "space": " " if i < len(parameter_variables)-1 else "",
            "true": instance['parameter_values'][varname],
        })
    components = []
    for i, state_var in enumerate(state_variables):
        components.append({
            "state_var": state_var,
            "state_expr": instance["ode_system"][state_var],
            "comma": ", " if i < len(state_variables)-1 else "",
        })
    measured_quantities = []
    for i, measure_var in enumerate(instance['measurement_variables']):
        measured_quantities.append({
            "measurement": measure_var,
            "measurement_expression": instance['measurements'][measure_var],
            "index": i+1,
            "comma": ", " if i < len(measurement_variables)-1 else "",
        })
    measured_quantities_amigo2 = []
    for i, measure_var in enumerate(instance['measurement_variables']):
        measured_quantities_amigo2.append({
            "measurement": measure_var,
            "measurement_expression": instance['measurements'][measure_var].replace('*', '.*'),
            "index": i+1,
            "comma": ", " if i < len(measurement_variables)-1 else "",
        })

    initial_conditions = []
    for i, state_var in enumerate(state_variables):
        initial_conditions.append({
            "value": instance['state_values'][state_var],
            "comma": ", " if i < len(state_variables)-1 else "",
        })


    settings = {
        "name": instance_name, #re.sub(".jl$", "" , instance_name),
        "states": states,
        "num_states": len(states),
        "measurements": measurements,
        "num_measurements": len(measurements),
        "parameters": parameters,
        "num_parameters": len(parameters),
        "components": components,
        "measured_quantities": measured_quantities,
        "measured_quantities_amigo2": measured_quantities_amigo2,
        "initial_conditions": initial_conditions,
        "time_start": instance["time"]["start"],
        "time_end": instance["time"]["end"],
        "duration": instance["time"]["end"] - instance["time"]["start"],
        "time_count": instance["time"]["count"],
        "lower_bound": args.config['SEARCH_BOUNDS'][0],
        "upper_bound": args.config['SEARCH_BOUNDS'][1]
    }

    if 'data' in instance:
        settings["data"] = '\n'.join([' '.join([str(instance['data'][j][i]) for j in range(1, len(instance['data']))]) for i in range(len(instance['data'][0]))])
        settings["data_with_time"] = '\n'.join([','.join([str(instance['data'][j][i]) for j in range(0, len(instance['data']))]) for i in range(len(instance['data'][0]))])

    return settings
    
